// <auto-generated />
using System;
using IMS.Modular.Modules.Issues.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IMS.Modular.Modules.Issues.Infrastructure.Migrations
{
    [DbContext(typeof(IssuesDbContext))]
    [Migration("20260424212140_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("IMS.Modular.Modules.Issues.Domain.Entities.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("Priority");

                    b.HasIndex("ReporterId");

                    b.HasIndex("Status");

                    b.ToTable("Issues", (string)null);
                });

            modelBuilder.Entity("IMS.Modular.Modules.Issues.Domain.Entities.Issue", b =>
                {
                    b.OwnsMany("IMS.Modular.Modules.Issues.Domain.ValueObjects.IssueActivity", "Activities", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ActivityType")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("IssueId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("IssueId");

                            b1.ToTable("IssueActivities", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("IssueId");
                        });

                    b.OwnsMany("IMS.Modular.Modules.Issues.Domain.ValueObjects.IssueComment", "Comments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("AuthorId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("IssueId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("IssueId");

                            b1.ToTable("IssueComments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("IssueId");
                        });

                    b.OwnsMany("IMS.Modular.Modules.Issues.Domain.ValueObjects.IssueTag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("IssueId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("IssueId");

                            b1.ToTable("IssueTags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("IssueId");
                        });

                    b.Navigation("Activities");

                    b.Navigation("Comments");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
