apiVersion: 1

policies:
  - orgId: 1
    receiver: IMS-Slack
    group_by: ["alertname", "severity"]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h
    routes:
      - receiver: IMS-Email
        matchers:
          - alertname =~ "LowStock|DiskMemoryCritical"
        repeat_interval: 4h
      - receiver: IMS-Slack
        matchers:
          - alertname =~ "High5xxRate|HighP99Latency|RabbitMQQueueGrowing"
        repeat_interval: 30m
